packages/mitmproxy/src/lib/proxy/common/util.js
packages/mitmproxy/test/utilTest.js

问题修复：解析IPv6时，hostname和port有误的问题修复。
fixes #217

bugfix: 解析IPv6时，hostname和port有误的问题修复。

---

packages/gui/extra/scripts/github.script
packages/mitmproxy/src/lib/monkey/index.js

1. 更新github油猴脚本：版本从 `1.6.8` 升级到 `2.5.19`；
2. 修复一处代码，以兼容新版本油猴脚本。
> 脚本来源：https://raw.githubusercontent.com/XIU2/UserScript/master/GithubEnhanced-High-Speed-Download.user.js

更新github油猴脚本：版本从 `1.6.8` 升级到 `2.5.19`

---

packages/core/src/config/index.js
packages/mitmproxy/src/lib/interceptor/impl/req/githubSpeedUp.js
packages/mitmproxy/src/lib/interceptor/impl/req/proxy.js
packages/mitmproxy/src/lib/interceptor/index.js

feature: 新增 githubSpeedUp.js，定制github的加速策略，目前加速了仓库内图片的访问速度。

feature: 新增 githubSpeedUp.js，定制github的加速策略，目前加速了仓库内图片的访问速度。

---

packages/core/src/config.js
packages/gui/src/view/mixins/plugin.js
packages/gui/src/view/pages/setting.vue

feature: 新增恢复出厂设置功能。
该功能，将会备份 `${user.home}/.dev-sidecar/config.json`，并恢复默认配置，重新加载远程配置，然后重启加速服务和代理服务。
无

feature: 新增恢复出厂设置功能。

---

packages/core/src/config/index.js
packages/gui/src/bridge/update/backend.js
packages/gui/src/bridge/update/front.js
packages/gui/src/view/pages/index.vue
packages/gui/src/view/pages/setting.vue

1. 检查更新功能，使用 github api 来获取版本数据
2. 自动检查更新功能，可配置化

feature: 1）检查更新功能，使用 github api 来获取版本数据；2）自动检查更新功能，可配置化。

---

packages/core/src/modules/plugin/node/config.js
packages/core/src/modules/plugin/node/index.js
packages/gui/src/view/pages/plugin/node.vue
packages/gui/src/view/pages/plugin/pip.vue

feature: npm命令可配置化。
fixes #317

feature: npm命令可配置化。

---

packages/gui/src/view/pages/plugin/pip.vue

Update(pip.vue): 添加更多镜像

---

packages/core/src/config/index.js
packages/core/src/modules/proxy/index.js

1. 添加了一些域名进入系统代理排除列表
2. 解决`ssh.github.com`无法访问的问题

 add(index.js): 添加了一些域名进入系统代理排除列表

---

packages/core/src/config.js
packages/core/src/config/index.js
packages/gui/src/view/pages/setting.vue

feature: 添加个人远程配置功能。
配置优先级说明：本地修改配置 > 个人远程配置 > 共享远程配置

feature: 添加个人远程配置功能。

---

packages/gui/src/view/pages/plugin/node.vue
packages/gui/src/view/pages/plugin/pip.vue
packages/gui/src/view/pages/setting.vue

optimize: 所有镜像按钮，鼠标移上可显示镜像URL
无

optimize: 所有镜像按钮，鼠标移上可显示镜像URL

---

packages/core/src/modules/proxy/index.js
packages/core/src/shell/scripts/set-system-proxy/index.js
packages/gui/src/view/pages/proxy.vue

feature: 系统代理页面，添加 `是否代理HTTP请求` 的配置项。

feature: 系统代理页面，添加 `是否代理HTTP请求` 的配置项。

---

packages/gui/src/view/pages/server.vue

feature: 加速服务，新增 `DNS服务管理` 页面，可自定义增删改 `DNS服务` 了

feature: 加速服务，新增 `DNS服务管理` 页面，可自定义增删改 `DNS服务` 了

---

packages/core/src/config/index.js
packages/gui/src/background.js
packages/gui/src/view/pages/setting.vue

feature: 可配置 `启动软件时是否打开窗口`
fixes #184

feature: 可配置 `启动软件时是否打开窗口`

---

packages/core/src/modules/plugin/overwall/config.js
packages/gui/src/view/pages/plugin/node.vue
packages/gui/src/view/pages/plugin/overwall.vue
packages/mitmproxy/src/lib/proxy/middleware/overwall.js
packages/mitmproxy/src/options.js

feature: 新增 `pac.txt`（即 `GFW` 列表）自动更新功能
fixes #346

feature: 新增 `pac.txt`（即 `GFW` 列表）自动更新功能

---

packages/core/src/config/index.js
packages/gui/src/view/pages/server.vue
packages/mitmproxy/src/lib/proxy/common/util.js
packages/mitmproxy/src/lib/proxy/middleware/overwall.js
packages/mitmproxy/src/lib/proxy/mitmproxy/createRequestHandler.js
packages/mitmproxy/src/lib/proxy/mitmproxy/createUpgradeHandler.js
packages/mitmproxy/src/lib/proxy/mitmproxy/index.js
packages/mitmproxy/src/options.js

feature: 请求超时时间和连接超时时间可配置化
fixes #71

feature: 请求超时时间和连接超时时间可配置化

---

packages/gui/package.json
packages/gui/src/background.js
packages/gui/src/background/powerMonitor.js
packages/gui/vue.config.js

解决 Windows 在重启后，电脑无法上网
fixes #109
无

bugfix: Windows操作系统，开着DS应用重启电脑后无法上网的问题修复

---

packages/gui/src/view/App.vue
packages/gui/src/view/composables/theme.js
packages/gui/src/view/pages/setting.vue

feat: follow system theme（跟随系统主题）

---

packages/mitmproxy/src/lib/proxy/tls/CertAndKeyContainer.js
packages/mitmproxy/src/lib/proxy/tls/FakeServersCenter.js
packages/mitmproxy/src/lib/proxy/tls/tlsUtils.js

optimize: 伪服务和伪证书作用域扩大到泛域名，而非单个域名，提升性能
fixes #417
无

optimize: 伪服务和伪证书作用域扩大到泛域名，而非单个域名，提升性能

---

packages/core/src/config/index.js
packages/core/src/utils/util.log.js
packages/core/src/utils/util.logger.js
packages/gui/src/view/pages/setting.vue

feature: 日志优化
1. 历史日志压缩保存；
2. 日志保留数和保存路径可配置化。
fixes #431

feature: 日志优化 1）历史日志压缩保存；2）日志保留数和保存路径可配置化。

---

packages/core/src/config/index.js
packages/core/src/utils/util.logger.js
packages/gui/src/view/pages/setting.vue

feature: 日志文件大小限制可配置化
fixes #442

feature: 新增日志文件大小限制功能
