README.md
FastGit has migrated to FastGit UK.
=> use new organisation name

packages/core/src/merge.js, packages/gui/src/view/components/settings.vue, packages/gui/src/view/pages/server.vue, packages/mitmproxy/src/lib/interceptor/impl/req/OPTIONS.js, packages/mitmproxy/src/lib/interceptor/impl/req/abort.js, packages/mitmproxy/src/lib/interceptor/impl/req/cacheReq.js, packages/mitmproxy/src/lib/interceptor/impl/req/proxy.js, packages/mitmproxy/src/lib/interceptor/impl/req/redirect.js, packages/mitmproxy/src/lib/interceptor/impl/req/sni.js, packages/mitmproxy/src/lib/interceptor/impl/req/success.js, packages/mitmproxy/src/lib/interceptor/impl/res/cacheRes.js, packages/mitmproxy/src/lib/interceptor/impl/res/script.js, packages/mitmproxy/src/lib/proxy/middleware/overwall.js, packages/mitmproxy/src/options.js, packages/mitmproxy/src/utils/util.match.js
1. feature: 在匹配拦截配置时，可匹配到多个 ‘域名匹配符’ 下的拦截配置；
2. optimize: 拦截配置中的redirect配置，可以使用绝对地址了；
3. optimize: 拦截配置中的redirect配置，可以使用 `${host}` 了，如 proxy 配置；
4. optimize: 拦截配置或远程配置中，可以配置某个配置项的值为 `[delete]`，来移除某个配置了；（原版本只有远程配置可以移除配置值为null的配置项）
1. 拦截配置如下：
```json
{
"*.github.com": {
".*": {
"sni": "baidu.com"
},
"xxx": {
"yyy": "zzz"
}
},
"github.com": {
"/.*/.*/releases/download/": {
"redirect": "gh.api.99988866.xyz/https://github.com",
"desc": "release文件加速下载跳转地址"
},
"xxx": "[delete]" // 域名直接匹配，优先级更高，将会删除 `*.github.com` 中的 xxx 配置项。
},
"collect.github.com": {
"/github/collect": {
"success": true,
"status": 204,
"desc": "采集数据，快速成功"
}
}
}
```
2. 当访问域名 `github.com` 时，将会匹配到：
```json
{
".*": {
"sni": "baidu.com"
},
"xxx": {
"yyy": "zzz"
},
"/.*/.*/releases/download/": {
"redirect": …
```
=> feature: 拦截配置功能，允许匹配到多个 ‘域名匹配符’ 下的拦截配置了，只要域名符合 ‘域名匹配符’。

packages/core/src/config/index.js
bugfix: 调整github油猴脚本的拦截配置，修复在先访问其他页面（如：issue、PR页面），再通过tab切换到code页面时，由于页面是局部刷新，导致油猴脚本未加载的问题。
fixes #288
=> bugfix: 调整github油猴脚本的拦截配置，修复在先访问其他页面（如：issue、PR页面），再通过tab切换到code页面时，由于页面是局部刷新，导致油猴脚本未加载的问题。

packages/mitmproxy/src/lib/interceptor/impl/res/response.js, packages/mitmproxy/src/lib/interceptor/index.js
feature: 新增 `response` 拦截器，目前暂时只支持替换响应头。
---
```json
{
"xxx.com": {
"/xxxxxxx.js": {
"response": {
"headers": {
"content-type": "application/javascript; charset=utf-8"
}
}
}
}
}
```
=> feature: 新增 `response` 拦截器，目前暂时只支持替换响应头。

packages/mitmproxy/src/lib/interceptor/impl/req/cacheReq.js, packages/mitmproxy/src/lib/interceptor/impl/req/requestReplace.js, packages/mitmproxy/src/lib/interceptor/impl/res/cacheRes.js, packages/mitmproxy/src/lib/interceptor/impl/res/responseReplace.js, packages/mitmproxy/src/lib/interceptor/impl/res/script.js, packages/mitmproxy/src/lib/interceptor/index.js
feature: 新增 requestReplace 拦截器，目前只支持替换请求头。
---
该拦截器配置方式：
```json
{
"github.com": {
"/xxxxx/yyyy": {
"requestReplace": {
"headers": {
"host": "gitee.com", // 替换请求头
"cookie": "[remove]", // 移除请求头（必须配置为 `[remove]` 才会移除，不能配置为null）
}
}
}
}
}
```
=> feature: 新增 requestReplace 拦截器，目前只支持替换请求头。

packages/mitmproxy/src/lib/proxy/mitmproxy/createRequestHandler.js, packages/mitmproxy/src/options.js
feature: 在 `script` 拦截器配置相对地址和绝对地址时，自动生成一些相关的辅助拦截配置，解决以下问题：
1. 避免跨域问题
2. 避免脚本内容类型限制问题
3. 避免绝对地址在接收代理请求时，由于请求头包含了源站点的一些信息而被拦截或重定向
原配置：
```json
{
"github.com": {
"^(/[^/.]{1,30}){2}([/?].*)?$": {
"script": [
"https://raw.githubusercontent.com/docmirror/dev-sidecar/scripts/github/monkey.js"
],
"desc": "加载DS仓库中的Github油猴脚本，加速clone和文件下载等。"
}
}
}
```
自动替换为：
```json
{
"github.com": {
"^(/[^/.]{1,30}){2}([/?].*)?$": {
"script": [
"/____ds_script_proxy____/httpsrawgithubusercontentcomdocmirrordevsidecarscriptsgithubmonkey.js"
],
"desc": "加载DS仓库中的Github油猴脚本，加速clone和文件下载等。"
}
},
"^/____ds_script_proxy____/httpsrawgithubusercontentcomdocmirrordevsidecarscriptsgithubmonkey\\.js$": {
"proxy": "https://raw.githubusercontent.com/docmirror/dev-sidecar/scripts/github/monkey.js",
"requestReplace": { …
```
=> feature: 在 `script` 拦截器配置相对地址和绝对地址时，自动生成一些相关的辅助拦截配置，避免相对地址和绝对地址引起的跨域问题和脚本内容类型限制问题。

packages/core/src/config/index.js, packages/mitmproxy/src/lib/interceptor/impl/res/script.js
feature: 篡改猴插件，可以自定义配置地址了。
---
配置方式如下：
```json
{
"github.com": {
"^(/[\\w-.]+){2,}/?(\\?.*)?$": {
// 自定义篡改猴插件地址配置
"tampermonkeyScript": "https://mirror.ghproxy.com/https://raw.githubusercontent.com/docmirror/dev-sidecar/scripts/tampermonkey.js",
"script": [
// Github油猴脚本
"https://mirror.ghproxy.com/https://raw.githubusercontent.com/docmirror/dev-sidecar/scripts/github/monkey.js"
]
}
}
}
```
=> feature: 篡改猴插件地址，可以自定义配置了。

packages/mitmproxy/src/lib/proxy/mitmproxy/createConnectHandler.js, packages/mitmproxy/src/lib/proxy/mitmproxy/createRequestHandler.js, packages/mitmproxy/src/lib/proxy/mitmproxy/dnsLookup.js
- optimize: DNS获取到的IP，如果测速未通过，则不使用该IP，直接使用域名发起请求。
- bugfix: 修复 `代理连接超时时，未关闭客户端socket连接` 的问题。
- optimize: `dns-lookup` 代码封装并优化日志，使 `connect` 和 `request` 复用 `dns-lookup` 的代码。
fixes #308
=> optimize: DNS获取到的IP，如果测速未通过，则不使用该IP，直接使用域名发起请求。

packages/gui/src/view/pages/server.vue, packages/mitmproxy/src/lib/speed/SpeedTester.js
IP测速页面调整：
1. bugfix: 测速未通过的IP却排在前面的问题修复
2. optimize: 测速IP后面直接显示DNS名称
=> IP测速页面调整：1）测速未通过的IP却排在前面的问题修复；2）测速IP后面直接显示DNS名称。

packages/core/src/config.js, packages/core/src/config/index.js, packages/gui/src/bridge/api/backend.js
optimize: 兼容使用 `1.7.3` 及以下版本的配置文件
> 由于 `1.8.0` 版本，对 `~/.dev-sidecar/config.json5` 和 `~/.dev-sidecar/setting.json5` 两个配置文件名进行了后缀名修改，由 `.json5` 修改为 `.json`，导致从`1.7.3` 及以下版本升级上来的用户，无法继续使用 `.json5` 配置文件中的内容，而产生了丢失配置的现象，现修复此问题。
=> optimize: 兼容使用 `1.7.3` 及以下版本的配置文件

packages/core/src/config.js, packages/gui/src/bridge/update/backend.js, packages/gui/src/bridge/update/front.js, packages/gui/src/view/pages/setting.vue, packages/gui/src/view/style/index.scss
optimize: 恢复出厂设置功能优化：
1. 备份个性化配置的同时，创建一个空的配置文件；
2. 恢复出厂时，提示如何找回个性化配置，如下截图：
=> optimize: 恢复出厂设置功能优化：1）备份文件的同时，创建一个空的原配置文件；2）恢复出厂时，提示如何找回个性化配置。

packages/core/src/config/index.js, packages/gui/src/background.js, packages/gui/src/view/pages/setting.vue
feature: `启动时窗口大小` 可配置化，默认值：`900 * 750`，最小值：`600 * 500`，最大值：`2400 * 2000`
=> feature: `启动时窗口大小` 可配置化

packages/core/src/modules/plugin/git/config.js, packages/core/src/modules/plugin/git/index.js, packages/gui/src/view/pages/plugin/git.vue
feature: `Git.exe`代理，支持排除自定义仓库地址，不进行代理
=> feature: `Git.exe` 代理，支持排除自定义仓库地址，不进行代理

packages/gui/src/background.js
feature: 按 `F12` 可以打开/关闭 `开发者工具` 了
optimize: 右键托盘小图标时，提示快捷键为 `F12`
=> feature: 按 `F12` 可以打开/关闭 `开发者工具` 了。

packages/mitmproxy/src/options.js, packages/mitmproxy/src/utils/util.match.js
1. feature: 拦截配置，支持排除配置（`exclusions`）了。
> 可通过 `通配符` 或 `正则` 大范围配置拦截，再通过 `exclusions` 小范围排除，方便配置。
=> feature: 拦截配置，支持排除配置（`exclusions`）了

packages/core/src/config/index.js, packages/gui/src/background.js, packages/gui/src/view/pages/setting.vue
feature: 添加显示/隐藏窗口的全局快捷键，默认：`Alt+S`
=> feature: 添加显示/隐藏窗口的全局快捷键，默认：`Alt+S`

README.md
README错误，更改旧淘宝npm域名为新的，旧的npm域名DNS已不再解析
=> README错误，更改旧淘宝npm域名为新的

packages/core/src/config/index.js, packages/gui/src/view/pages/server.vue, packages/mitmproxy/src/lib/proxy/common/util.js, packages/mitmproxy/src/lib/proxy/compatible/compatible.js, packages/mitmproxy/src/lib/proxy/mitmproxy/createConnectHandler.js, packages/mitmproxy/src/lib/proxy/mitmproxy/createRequestHandler.js, packages/mitmproxy/src/lib/proxy/tls/FakeServersCenter.js, packages/mitmproxy/src/options.js
feature: 新增兼容程序，在遇到部分特定异常时，通过自动调整参数达到自动兼容的效果
目前已处理问题：
1. 问题：ws请求，建立连接时，报错：`ERR_SSL_INVALID_LIBRARY_(0)`
解决方案：自动切换为使用http协议进行连接
2. 问题：当对应站点使用了自签名证书时，请求报错：`DEPTH_ZERO_SELF_SIGNED_CERT`
解决方案：请求时不校验ssl
后续，还会继续增加一些异常的自动兼容处理。
fixes #337
=> feature: 新增兼容程序，在遇到部分特定异常时，通过自动调整参数达到规避异常的目的

packages/core/src/config/index.js, packages/gui/src/view/App.vue, packages/gui/src/view/components/tree-node.vue, packages/gui/src/view/pages/help.vue, packages/gui/src/view/router/index.js, packages/gui/src/view/router/menu.js, packages/gui/src/view/style/index.scss
feature: 新增可配置化的 `帮助中心` 页面
可通过 `help.dataList` 配置项进行配置，也可配置在远程配置文件中：
```json
{
"help": {
"dataList": [
{
"title": "1、主题xxxx",
"children": [
{
"title": "1）标题标题标题标题标题",
"url": "https://github.com/docmirror/dev-sidecar/wiki"
}
]
},
{
"title": "2、主题yyyy",
"children": [
{
"title": "1）标题1",
"url": "https://github.com/docmirror/dev-sidecar/wiki"
},
{
"title": "2）标题标题标题标题标题",
"url": "https://github.com/docmirror/dev-sidecar/wiki"
}
]
},
{
"title": "3、主题zzzz",
"children": [
{
"title": "1）标题1",
"url": "https://github.com/docmirror/dev-sidecar/wiki"
},
{
"title": "2）标题标题标题标题标题",
"url": "https://github.com/docmirror/dev-sidecar/wiki"
},
{
"title": "3）标题标题标题标题标题",
"url": "https://github.com/docmirror/dev-sidecar/wiki"
}
]
}
]
}
}
```
fixes #404
=> feature: 新增可配置化的 `帮助中心` 页面

.github/workflows/build-and-release.yml, .github/workflows/test-and-upload.yml, package.json, packages/core/package.json, packages/gui/package.json, pnpm-lock.yaml
fixes #409
fixes #413
fixes #414
=> bugfix: 修复缺少 `vcruntime` 导致导入 `napi-rs` 编译的原生模块失败的问题

packages/cli/src/mitmproxy.js, packages/core/src/utils/util.log.js, packages/core/src/utils/util.logger.js, packages/gui/src/bridge/mitmproxy.js, packages/gui/src/utils/util.log.js, packages/mitmproxy/src/utils/util.log.js
bugfix: 多进程导致日志记录异常的问题修复
fixes #433
无
=> bugfix: 多进程导致日志记录异常的问题修复

packages/core/src/config/index.js, packages/gui/src/background.js, packages/gui/src/bridge/on-close/front.js, packages/gui/src/view/api.js
optimize: linux允许隐藏窗口，但必须先设置好快捷键
> 注：以前不允许linux关闭窗口是因为linux没有系统托盘，无法呼出窗口，现在有快捷键了，可以呼出窗口了。
fixes #259
fixes #444
=> optimize: linux允许隐藏窗口了，前提是先设置好快捷键

doc/linux.md
=> doc: 添加特殊linux安装说明
